---
title: North Range Concerned Citizens
timezone: Pacific/Pago_Pago
collections:
  articles:
    title: Articles
    output: true
  events:
    title: Events
    output: true
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
owner: North Range Concerned Citizens
description: We are a coalition of Commerce City neighborhoods that firmly believes  industrial
  activity is incompatible with residential areas anywhere.
baseurl: 
url: 
twitter_username: NorthRangeCC
github_username: 
address:
- line: 
- line: 
telephone: 
copyright: 
email: northrangeconcernedcitizens@gmail.com
google_api_key: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
